name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# FIXME: Figure out why $PWD expansion fails...
env:
  CARGO_TERM_COLOR: always
  OPENTOK_LIB_DIR: /home/runner/work/opentok-rs/opentok-rs/libopentok_linux_llvm_x86_64/lib
  LD_LIBRARY_PATH: /home/runner/work/opentok-rs/opentok-rs/libopentok_linux_llvm_x86_64/lib

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SDK
      run: |
        wget https://tokbox.com/downloads/libopentok_linux_llvm_x86_64-2.19.1
        tar xf libopentok_linux_llvm_x86_64-2.19.1
        rm -f libopentok_linux_llvm_x86_64-2.19.1
        sudo apt update
        sudo apt -y install clang libc++-dev libc++abi-dev python3-pip ninja-build build-essential flex bison
        sudo python3 -m pip install meson
        git clone https://gitlab.freedesktop.org/gstreamer/gstreamer.git
        cd gstreamer/
        meson build/ --auto-features=disabled --prefix=/usr
        sudo ninja -C build install
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --features gstreamer-utils --verbose -- --test-threads=1
      env:
        OPENTOK_KEY: ${{ secrets.OPENTOK_KEY }}
        OPENTOK_SECRET: ${{ secrets.OPENTOK_SECRET }}
